Use Figma API to download icons
StackExchange/Stacks-Icons pull request #153
Opened 2022-10-03 18:42 UTC by abovedave

An idea to optimize the workflow - grab the components directly from the [Figma API](https://www.figma.com/developers/api#get-files-endpoint) so we save folks from needing to download the icon first from the Figma doc.

Also creates a preview for the readme with this data, replacing the outdated statically generated image.

2022-10-04 15:24 UTC, b-kelly reviewed
Oooh, I love this idea! Let me test it out locally a bit and I'll leave a more complete review.

2022-10-05 12:59 UTC, abovedave commented
Another idea here - could we just fold this into the build step for the main Stacks repo? Put another way, if this is worthwhile, is there a need for a separate repo?

2022-10-05 17:46 UTC, b-kelly commented
@abovedave That's an excellent point, actually. As of right this moment, we'd like to keep the repos separate because they build two different npm packages. We've been toying with the idea of moving Stacks to a mono repo though, in which case it'd make a lot of sense to fold this one in with that.

2022-10-05 17:49 UTC, b-kelly requested changes
Reviewing the code, I really like this approach. It lets us use Figma as the source of truth instead of the other way around (duplicating our icons into Figma). I have some concerns about "blindly" just pulling in any given bit of "code" into this repo, but I have some tweaks locally that will solve this. I'll add more details when I commit my changes to this branch and we can go back and forth on the details/implementation at that point.

2022-10-05 18:18 UTC, b-kelly commented
@abovedave I made two change to the repo:
1. Add support for storing the token in a `.env` file (convenient for local dev, you can keep doing your method as well)
2. Make all icons / updates _opt-in_ by including their name and hash in the `src/definitions.ts` file

The reasons I'm going with opting in are:
1. The build script now won't pull in any given component that happens to be in that page
  a. this is important for security reasons and for reasons outlined below
2. Rejecting icons that have a hash mismatch ensure that we are controlling/auditing all icon updates
  a. this provides transparency as we now know exactly _which_ icons have been updated
  b. the extra transparency helps us to not miss any updates for auditing / changelog generation
  c. all mismatched hashes will print out an error with the new hash so it'll be easy to update the definitions

2022-10-05 18:19 UTC, b-kelly commented
@StackExchange/stacks What do y'all think about Dave's approach? I'm personally a fan and I think that I've addressed all security concerns

2022-10-06 10:04 UTC, abovedave commented
The hash is a fantastic idea - I was wondering what adding a new icon would even look like in the repo history apart from just updating the readme, so that is much clearer and intentional.

2022-10-07 12:15 UTC, giamir reviewed
Great work! 🙌
I am a bit of an automation junky myself. I like that we are taking steps to hand over to the computers these tedious and error prone tasks. 🎉
I also like a lot the integrity check Ben added for the individual images. It gives us an extra layer of confidence in terms of security and reliability.

I added 2 or 3 actionable comments in the PR. Nothing major but let me know what you think. In case you agree I can also take care of making the adjustments if you prefer.

In terms of maintainability I think we are reaching a level of complexity where it could pay off to take a small break and think a bit about the overall design.
For example at the moment we don't have a clear separation of concerns across the files and functions (e.g. we call apis, calculate hashes, write to disk in the same functions).
If we see ourselves touching these scripts again in the future maybe it could be the right time to start breaking down the server.ts file and create dedicated services and clients layers. 

The pragmatic in me say that for now we could leave things as they are without big refactorings. Thoughts?

2022-10-07 12:15 UTC, giamir commented on src/fetchFigmaComponents.ts
> +import axios from "axios";
I would recommend to keep the file convention consistent with the rest of the codebase (which seems to be kebab-case). `fetchFigmaComponents.ts` becomes `fetch-figma-components.ts`

2022-10-07 12:15 UTC, giamir commented on src/fetchFigmaComponents.ts
> +    params: { format: "svg", ids: componentIds.slice(0, -1) },
At first glance I struggled to understand why we were doing a slice operation here. 
What do you think about making the `componentIds` variable an array of ids instead of a string and then perform a `componentIds.join(",")`?
Alternatively we could also consider removing the `componentIds` variable all together and rely only on the `names` dictionary. `Object.keys(names).join(',')`.
What do you think is best for maintainability/readability?

2022-10-07 12:15 UTC, giamir commented on server.ts
> +    return; //can't continue without the icons
I think it is important here that the process exit with a code different from 0. For example pipeline tools would just print a console error and give us a false feeling that everything worked correctly. My recommendation would be to remove the try catch statement all together. 

Side note:
We do actually a bunch of error handling in this file which I don't see as strictly necessary since we are only printing in console and swallow the error. If something goes wrong with the script we should probably let the process exit (the error message and stack trace will be printed out anyway) - what do you think?

2022-10-07 17:23 UTC, b-kelly commented on server.ts
> +    return; //can't continue without the icons
Agreed. This is a bit of legacy left over from some earlier iterations. I've cleaned up the exception handling a bit, along with making the output a bit more readable as well.

2022-10-07 17:28 UTC, b-kelly commented on src/fetchFigmaComponents.ts
> +    params: { format: "svg", ids: componentIds.slice(0, -1) },
Dave originally wrote it as you mentioned. When rewriting that code a tad, I did this as a micro-optimization. As you say, it isn't immediately more readable, I don't mind changing it back. Good call on simply reusing the keys - that's even better.

2022-10-07 17:30 UTC, b-kelly commented
@giamir Thank you for the review! I made all the suggested changes. Regarding a refactor, I agree that this is _just_ big enough that it would benefit from that, but I'd like to do it as a follow-up PR. If you'd like to tackle that as part of your onboarding, that might be a good afternoon project.

2022-10-07 17:45 UTC, b-kelly requested changes
On auditing the code, it looks like there are a few extra / missing / improperly named icons. I made changes / added comments to the `definitions.ts` file to reflect this.

@abovedave These will need to be fixed on the Figma side before we merge. The extra ones are ok to leave in - we can simply uncomment those in a follow-up PR to include them 🎉.

2022-10-11 19:57 UTC, b-kelly approved these changes
After some tweaks in Figma, this is finally good to go out! Also added a few console warnings when a component exists in Figma, but not the definitions (and vice versa).

Thank you @abovedave for kicking this off, it's going to be a huge improvement to the designer's workflow.

2022-10-12 15:53 UTC, merged